### ISSUE TITLE
why poc?

### ISSUE THREAD

**Issue by yassern** [jjazvdo/poc_angular#1]
i don't understand the name of the repository
help please

**Comment by jjazvdo** [comment]
Proof of concept (PoC) is a realization of a certain method or idea in order to demonstrate its feasibility, or a demonstration in principle with the aim of verifying that some concept or theory has practical potential. A proof of concept is usually small and may or may not be complete. 

Or, PoC is utilizado para se referir aos gays considerados mais afeminados e chamativos. 

HHAHAHHA

**Comment by yassern** [comment]
lol aheuaheu
